name: Run tests

on: [push]

jobs:
  tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: ctype, bcmath, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Setup environment
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run tests
        run: php artisan test

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,action,workflow,job,took
          job_name: Run PHPUnit Tests
          author_name: GitHub Actions
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
